### ISSUE TITLE
运行train_merge时出错

### ISSUE THREAD

**Issue by zhaochuanyun** [colabin/Alibaba-Cloud-German-AI-Challenge-2018#1]
你好，运行train_merge时出错，是不是版本有问题？能否问下你用的tensorlayer、tensorflow版本分别是多少呢

/home/mvpzhao/anaconda3/bin/python /home/mvpzhao/tools/python-workspace/Alibaba-Cloud-German-AI-Challenge-2018/train_merge.py
/home/mvpzhao/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/mvpzhao/tools/python-workspace/Alibaba-Cloud-German-AI-Challenge-2018/train_merge.py", line 46, in <module>
    net = get_resnet(images, 100, type='ir', w_init=w_init_method, trainable=trainable, keep_rate=dropout_rate)
  File "/home/mvpzhao/tools/python-workspace/Alibaba-Cloud-German-AI-Challenge-2018/net/L_Resnet_E_IR.py", line 421, in get_resnet
    scope='resnet_v1_%d' % num_layers)
  File "/home/mvpzhao/tools/python-workspace/Alibaba-Cloud-German-AI-Challenge-2018/net/L_Resnet_E_IR.py", line 323, in resnet
    net = BatchNormLayer(net, act=tf.identity, name='bn0', is_train=True, trainable=trainable)
  File "/home/mvpzhao/tools/python-workspace/Alibaba-Cloud-German-AI-Challenge-2018/net/L_Resnet_E_IR.py", line 113, in __init__
    Layer.__init__(self, name=name)
  File "/home/mvpzhao/anaconda3/lib/python3.6/site-packages/tensorlayer/decorators/deprecated_alias.py", line 24, in wrapper
    return f(*args, **kwargs)

**Comment by colabin** [comment]
tensorflow是最新的，可能和tensorflayer有关，tensolayer是1.7版本
